language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: jffelsinger@gmail.com
  api_key:
    secure: FAkNDZdQL+CIpyO8lBVbxAmTMZ06Y3/MaZNF2NW0hYSXPJtL3HeZplUm2Nuhfm17dfBXoF09bO+18J95d5ipG5kQAdfD746biI6fhBUk8suzq8fyABjm361WaK7Mdn0AZD445fsAKluUX+Lg6odV4OTVIGpJTAHmVE/1MNjTqKQ=
  on:
    tags: true
    repo: jfelsinger/couch-cushion
